// Called api on firebase . Here is example of virtual data
final List<Map<String, String>> hotelData = [
  {
    'id': '1234',
    'image': 'http://res.cloudinary.com/dfa17qrac/image/upload/v1755243539/images/mgppcv00ezxvztuspqaj.jpg',
    'name': 'The Horizon Retreat',
    'location': 'Los Angeles, CA',
    'currentPrice': '450',
    'lastPrice': '450',
    'roomType': 'vip',
    'trffic': '120',
    'ratting': '4.5',
  },
  {
    'id': '1234',
    'image': 'http://res.cloudinary.com/dfa17qrac/image/upload/v1755243539/images/mgppcv00ezxvztuspqaj.jpg',
    'name': 'Ocean Breeze Suites',
    'location': 'Miami, FL',
    'currentPrice': '380',
    'lastPrice': '450',
    'roomType': 'vip',
    'trffic': '120',
    'ratting': '4.2',
  },
  {
    'id': '1234',
    'image': 'http://res.cloudinary.com/dfa17qrac/image/upload/v1755243539/images/mgppcv00ezxvztuspqaj.jpg',
    'name': 'Mountain View Lodge',
    'location': 'Denver, CO',
    'currentPrice': '500',
    'lastPrice': '450',
    'roomType': 'vip',
    'trffic': '120',
    'ratting': '4.8',
  },
];
