name: hotel_booking_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  calendar_date_picker2: ^2.0.1
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0

  # firebase
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_storage: ^13.0.0

  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  go_router: ^16.2.0
  google_fonts: ^6.3.0
  #authentication with google
  google_sign_in: ^6.3.0
  infinite_scroll_pagination: ^5.1.1
  intl: any
  provider: ^6.1.5
  readmore: ^3.0.0
  shared_preferences: ^2.5.3
  shimmer_animation: ^2.1.0
  smooth_page_indicator: ^1.2.1
  visibility_detector: ^0.4.0+2


dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80
  assets:
    enabled: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/onboarding/
    - assets/images/icon/
    - assets/images/home/
    - assets/images/avatar/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoApp.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
