name: hotel_booking_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.3.0
  device_preview: ^1.2.0
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.2.0
  shimmer_animation: ^2.1.0
  readmore: ^3.0.0
  shared_preferences: ^2.5.3
  go_router: ^16.2.0
  calendar_date_picker2: ^2.0.1
  visibility_detector: ^0.4.0+2
  flutter_dash: ^1.0.0

  # firebase
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0

  #authentication with google
  google_sign_in: ^6.3.0

  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD

  flutter_gen_runner:
  build_runner:

  flutter_lints: ^5.0.0

flutter_gen:
  assets:
    enabled: true
    package_parameter_enabled: true
    line_length: 80
    output: lib/gen/assets.gen.dart
=======

  build_runner:
  flutter_gen_runner:

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  assets:
    enabled: true

>>>>>>> feature/section_request_booking

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/onboarding/
    - assets/images/icon/
    - assets/images/home/
    - assets/images/avatar/
    - assets/images/
