name: widgetbook_HotelBookingApp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  hotel_booking_app:
    path: ../
  flutter:
    sdk: flutter
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.15.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/icon/
    - assets/images/home/
    - assets/images/avatar/
    - assets/images/
