// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmErdOvmxjRQqdt3FPYA8OrFsbuX6zqak',
    appId: '1:623338189246:web:e67cdeef427655cd1ac9ef',
    messagingSenderId: '623338189246',
    projectId: 'hotel-booking-app-a9305',
    authDomain: 'hotel-booking-app-a9305.firebaseapp.com',
    storageBucket: 'hotel-booking-app-a9305.firebasestorage.app',
    measurementId: 'G-DR9PF9FFLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifJGP_SQzY5PescGPj5DGhzh9rt3Ut_I',
    appId: '1:623338189246:android:917a7d076e1290581ac9ef',
    messagingSenderId: '623338189246',
    projectId: 'hotel-booking-app-a9305',
    storageBucket: 'hotel-booking-app-a9305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZTAfT6bOjWUOpN5yc0kuUXmF2TDqu4Og',
    appId: '1:623338189246:ios:60907748de4ce0dc1ac9ef',
    messagingSenderId: '623338189246',
    projectId: 'hotel-booking-app-a9305',
    storageBucket: 'hotel-booking-app-a9305.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZTAfT6bOjWUOpN5yc0kuUXmF2TDqu4Og',
    appId: '1:623338189246:ios:60907748de4ce0dc1ac9ef',
    messagingSenderId: '623338189246',
    projectId: 'hotel-booking-app-a9305',
    storageBucket: 'hotel-booking-app-a9305.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmErdOvmxjRQqdt3FPYA8OrFsbuX6zqak',
    appId: '1:623338189246:web:056c86fb5bd77ce71ac9ef',
    messagingSenderId: '623338189246',
    projectId: 'hotel-booking-app-a9305',
    authDomain: 'hotel-booking-app-a9305.firebaseapp.com',
    storageBucket: 'hotel-booking-app-a9305.firebasestorage.app',
    measurementId: 'G-PRVJPF9S1M',
  );
}
